name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: mkdist
      run: ./mkdist.sh
    - name: cd gkylzero-dist
      run: cd gkylzero-dist    
    - name: make
      run: make
    - name: make check
      run: make check
