name: Linux Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install-deps 
      run: cd install-deps; ./mkdeps.sh --build-openblas=yes --build-superlu=yes; cd ..
    - name: make
      run: make CC=clang -j
    - name: make check
      run: make CC=clang check
